### ISSUE TITLE
plain url in markdown are not clickable in the generated html file

### ISSUE THREAD

**Issue by jdhao** [wzpan/hexo-renderer-pandoc#18]
I have noticed that this renderer use the input format `-f markdown` instead of `-f gfm`. So the plain url in the markdown file are rendered as text in the html output. I think it is better to change the default to `-f gfm`. Just a suggestion.

**Comment by wzpan** [comment]
@jdhao have you tried to use the `<>` tag?

**Comment by jdhao** [comment]
What do you mean by `<>` tag? In my post, I just write something like:
```
you can use www.google.com to search for your question.
```

But, one disadvantage of the `gfm` format is that it does not support LaTeX equations. So I think the default `markdown` maybe good  :)
