### ISSUE TITLE
extra values not passed to pandoc

### ISSUE THREAD

**Issue by laBecasse** [wzpan/hexo-renderer-pandoc#19]
Hi,
Extra values of the configuration are passed to pandoc, because this line is commented : 
https://github.com/wzpan/hexo-renderer-pandoc/blob/fedc51c844c508dda6102d0897d6178dd41ec1bd/index.js#L26
Can you please uncomment it. 
Thank for all.

**Comment by wzpan** [comment]
@laBecasse Thank you for pointing out that. Fixed.

**Comment by ghost** [comment]
Thank a lot for the update
