### ISSUE TITLE
how to get metadata?

### ISSUE THREAD

**Issue by mcepl** [wzpan/hexo-renderer-pandoc#2]
Hi, I have this source in `rST`:

``` rst
title: 'Oh, really?'                                                            
categories:                                                                     
  - computer                                                                    
date: 2011-03-29 07:54:00                                                       
tags:                                                                           
---                                                                             

.. image:: http://1.bp.blogspot.com/-FicWNUhziTc/TZFzFKHBfqI/AAAAAAAAAv4/zB2N6X-B2sc/s1600/spreadfirefox.png
    :scale: 66%                                                                 
    :align: center                                                              

So, `spreadfirefox.com`_ which is known to be a PR tool of the Firefox          
community proudly offers old version of Firefox? (fortunately, these            
buttons lie, it really leads to firefox.com which offers the real               
thing). Interesting.                                                            

.. _`spreadfirefox.com`:                                                        
    http://www.spreadfirefox.com/                                               
```

Pure generation of HTML works just fine, but I don't know how to make hexo to get proper metadata (pariclarly it makes post dated by the date it has been generated, not the date mentiond in the `date:` field). It seems your renderer just runs the text through `pandoc`, but it doesn'ŧ seem to be parsing metadata from anywhere.

**Comment by wzpan** [comment]
The meta data is supposed to be processed by theme rather than renderer.

**Comment by mcepl** [comment]
> The meta data is supposed to be processed by theme rather than renderer.

Why then setting data works with `.md` files and not with `.rst` (processed by your renderer)? Meaning, what do you mean by "theme"? The code in `themes/` directory or something in the core of hexo?

**Comment by wzpan** [comment]
> it makes post dated by the date it has been generated, not the date mentiond in the date: field

Do you mean that by using this renderer Hexo will not able to take use of the meta data _i.e._ front matters properly? I think that shouldn't be caused by renderers.

Have you tried to embrace quotation marks between date info? For example:

``` plain
date:  "2011-03-29 07:54:00"
```

**Comment by mcepl** [comment]
Yes, thanks. Both

```
date: "2011-03-29 07:54:00"
```

and

```
date: 2011-03-29T07:54:00
```

(which is actually proper ISO format, isn't it?) works.
