### ISSUE TITLE
Code sections lose if update this renderer to 0.2.4

### ISSUE THREAD

**Issue by Yuki-Nagato** [wzpan/hexo-renderer-pandoc#21]
It works well in version 0.2.2, but all of the code sections (surrounded by "```") will lose if update to version 0.2.4.

Pandoc version: 2.3.

My hexo website code can be found at https://github.com/Yuki-Nagato/Yuki-Nagato.github.io

**Comment by wzpan** [comment]
Maybe its caused by this issue #20 .

Can you try to downgrade to 0.2.3 and see whether it solves your problem?

npm install --save hexo-renderer-pandoc@0.2.3

**Comment by zawnpn** [comment]
> Maybe its caused by this issue #20 .
> 
> Can you try to downgrade to 0.2.3 and see whether it solves your problem?
> 
> npm install --save hexo-renderer-pandoc@0.2.3

the same problem as @Yuki-Nagato , and get fixed after downgrading

**Comment by peniridis** [comment]
I have the same problem, but works well in 0.2.3
### Env
Hexo 3.7
NexT 6.4.1
Hexo-renderer-pandoc 0.2.4

**Comment by Yuki-Nagato** [comment]
> 
> 
> Maybe its caused by this issue #20 .
> 
> Can you try to downgrade to 0.2.3 and see whether it solves your problem?
> 
> npm install --save hexo-renderer-pandoc@0.2.3

Works well in 0.2.3
