### ISSUE TITLE
Duplicate note reference problem

### ISSUE THREAD

**Issue by sli1989** [wzpan/hexo-renderer-pandoc#24]
hello, `npm install hexo-renderer-pandoc@0.2.3 --save` works last time.

but today failed for

```
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Error: pandoc: Duplicate note reference `1' "source" (line 502, column 1)

    at ChildProcess.<anonymous> (/builds/sli1989/sli1989.gitlab.io/node_modules/hexo-renderer-pandoc/index.js:84:20)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:886:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
ERROR: Job failed: exit code 1
```

do u know what's going on?

---

- I though it's the problem of footnotes' id. but when i [deleted all new footnotes ](https://gitlab.com/sli1989/sli1989.gitlab.io/commit/be72d1af8180177ef8a8bd5bf18c24834fae82f5) which are added in this [commit](https://gitlab.com/sli1989/sli1989.gitlab.io/commit/a8849d2c0e3d883282ec53fc3292b707457ec1d0), it still not work.
- i tested with old next version, it still not work.

**Comment by wzpan** [comment]
Can you provide the markdown file that causes such problem?

**Comment by sli1989** [comment]
I located this section for the mistake.

```
但<font color=red> 关于行内代码，确实还存在一点问题</font>。因为kramed只是提高了LaTeX公式渲染的优先级，使类似 ``` 'formula' ```的语法不会被Markdown引擎替换，从而可以正确的被渲染成LaTeX公式。也就是说，对于kramed而言，出现 ``` ` ``` 符以后的两个 ``` $ ``` 符之间的部分才会被kramed认为是行内公式。要解决这个问题需要修改kramed的渲染机制。
```

any suggestion for the markdown grammar?

**Comment by wzpan** [comment]
Why use three backslash(`) rather than one backslash to render code?

Besides, you can try to use [raw plugin](https://hexo.io/docs/tag-plugins#Raw) in hexo.

This issue is not an issue of hexo-renderer-pandoc.

**Comment by sli1989** [comment]
yeah, i use three backslash for the misunderstanding backslash and '. 
thanks.
