### ISSUE TITLE
图片块解析错误！

### ISSUE THREAD

**Issue by siaimes** [wzpan/hexo-renderer-pandoc#34]
https://github.com/theme-next/hexo-theme-next/issues/857

**Comment by curbengh** [comment]
My summary of the issue:
when having [these lines](https://pastebin.com/ny85ErDV) (a code block immediately followed by image embed) in a post.md, the rendered result includes undesired caption,
![1](https://user-images.githubusercontent.com/43627182/61428720-8aad1980-a962-11e9-930b-2e4a7db1f02b.png)

```html
<figure class="highlight plain"><table><tr><td class="code"><pre><span class="line">code block</span><br></pre></td></tr></table></figure>
<figure>
<img src="https://postimgs.org/img/logo.png" alt="" /><figcaption>another thing</figcaption>
</figure>
```

but no caption when [code block + image + code block](https://pastebin.com/sJCzfBT8),
![2](https://user-images.githubusercontent.com/43627182/61428726-8f71cd80-a962-11e9-972a-e413d311a06f.png)

also no caption with [image + code block](https://pastebin.com/yMzt7ZWP)
![3](https://user-images.githubusercontent.com/43627182/61428730-93055480-a962-11e9-9a7c-124e03dfcff8.png)

I'm using v0.3.0 with pandoc 2.7.3

---

It seems to be an [intended feature](https://pandoc.org/MANUAL.html#images) of pandoc. There are two ways to disable the caption,

1. Through hexo's _config.yml:
```yml
pandoc:
  extensions:
    - '-implicit_figures'
```

2. Add a backslash and a space after image embed:
```markdown
![alt text](https://postimgs.org/img/logo.png)\ 
```

**Comment by siaimes** [comment]
Ok, I know what to do. Thank you guys for answering my questions, thank you very much.

**Comment by raytroop** [comment]
```
pandoc:
   extensions:
     - '-implicit_figures'
  ```
**don't** in *hexo-renderer-pandoc  0.5.0*

Can any give suggestion ?

**Comment by Ritsuka314** [comment]
the
``` yaml
pandoc:
  extensions:
```
interface has been deprecated. Instead, use 
``` yaml
pandoc:
  args:
```

See the following section of readme file for more details
https://github.com/hexojs/hexo-renderer-pandoc?tab=readme-ov-file#args

**Comment by raytroop** [comment]
@Ritsuka314 

Thanks,

but
```yaml
pandoc:
  args: ['-implicit_figures']
```

don't work for hexo-renderer-pandoc 0.5.0
