### ISSUE TITLE
hexo s error

### ISSUE THREAD

**Issue by Broduker** [wzpan/hexo-renderer-pandoc#36]
when use ``hexo s``, something was wrong
```bash
[ERROR][hexo-renderer-pandoc] pandoc exited with code 9: pandoc: Unknown extension: smart
```
Some people on the Internet said that it may be related to Pandoc's ``smart`` parameter, which is in the ``node_modules\hexo-renderer-pandoc\index.js`` file.

**Comment by Ritsuka314** [comment]
hi, could you check your pandoc version so i can reproduce your issue? also does using version above 2.0 fixes your issue?



---Original---

**Comment by Broduker** [comment]
> hi, could you check your pandoc version so i can reproduce your issue? also does using version above 2.0 fixes your issue?
> […](#)
> ---Original--- From: "Broduker"<notifications@github.com&gt; Date: Mon, Nov 18, 2019 11:55 AM To: "wzpan/hexo-renderer-pandoc"<hexo-renderer-pandoc@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [wzpan/hexo-renderer-pandoc] hexo s error (#36) when use hexo s, something was wrong [ERROR][hexo-renderer-pandoc] pandoc exited with code 9: pandoc: Unknown extension: smart Some people on the Internet said that it may be related to Pandoc's smart parameter, which is in the node_modules\hexo-renderer-pandoc\index.js file. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

pandoc version ``pandoc-2.7.3-windows-x86_64``

**Comment by Broduker** [comment]
发现作者是中国人，那我就用中文仔细陈述一遍吧。
我就是按照步骤先从官网下载了``pandoc-2.7.3-windows-x86_64``，并进行了安装
然后按照说明卸载原有的渲染器 `hexo-renderer-marked`，并安装了``hexo-renderer-pandoc``

```sh
uninstall hexo-renderer-marked
install hexo-renderer-pandoc 
```

然后在 `next/_config.yml` 中将 `mathjax` 的 `enable` 值设为``true``。

但是运行``hexo s``出现如上所述错误。上网查阅发现有人可能遇到了相似的问题，给出的解决办法为
将``node_modules\hexo-renderer-pandoc\index.js``中的
```javascript
var args = [ '-f', 'markdown-smart'+extensions, '-t', 'html-smart', math]
```
改成
```javascript
var args = [ '-f', 'markdown'+extensions, '-t', 'html', math]
```
修改后确实没有报错，参考的文章[Hexo 搭建个人博客指南]( https://www.jianshu.com/p/c9beedaf08e4 )

**Comment by Broduker** [comment]
hexo版本是4.0.0

**Comment by Ritsuka314** [comment]
好的。开完seminar回来就给你整。



---Original---

**Comment by Ritsuka314** [comment]
posting this for myself
https://zhuanlan.zhihu.com/p/58392526




---Original---

**Comment by Ritsuka314** [comment]
@Broduker 您好，我尝试使用以下命令

`<...>\pandoc-2.7.3-windows-x86_64\pandoc.exe -f markdown-smart -t html-smart source\_posts\hello-world.md
`

渲染成功没有报错。

可否再次确认你使用的 pandoc 版本？尤其是你安装的版本是否是命令行中搜索到的那个？请于回复中附上运行命令 `pandoc -v` 的结果。另外也请附上 `_config.yml` 以及 `package.json`.

**Comment by Broduker** [comment]
哦，好像真是版本的问题，在git bash中查看版本的结果如下，跟我单独安装的版本确实不一样
```bash
$ pandoc -v
pandoc.exe 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: C:\Users\shens\AppData\Roaming\pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```
这是我在安装hexo默认已经下载的吗，或者什么其他软件，之前确实没有单独下载过。那这样的话怎么替换这个版本呢

**Comment by Ritsuka314** [comment]
那应该是PATH环境变量没配置好



---Original---

**Comment by Broduker** [comment]
好的，我尝试改改

**Comment by Ritsuka314** [comment]
你这个1.xx的不是安装hexo的时候自带的。在windows系统环境变量里修改PATH，把老版本的pandoc路径删了，2.7.3的加进去



---Original---

**Comment by Broduker** [comment]
好的，多谢

**Comment by Ritsuka314** [comment]
整不明白再找我哈。要是整好了的话麻烦把issue关了，我不太喜欢关别人的issue



---Original---

**Comment by Broduker** [comment]
ok

**Comment by Broduker** [comment]
找到了pandoc 1.19.2.1的来源，是anaconda3中集成的，卸载或升级包版本后问题解决，不过部分镜像源没有2.0以上版本，需要手动查找。
感谢答主，那我就把issue关了

**Comment by sadofriod** [comment]
补充一个手动安装pandoc最新版的方式（对于Ubuntu）:
+  卸载原本的`sudo apt remove pandoc`
+  在任意目录下下载`wget https://github.com/jgm/pandoc/releases/download/2.17.1.1/pandoc-2.17.1.1-1-amd64.deb`
+  手动安装`sudo dpkg -i pandoc-2.17.1.1-1-amd64.deb`
