### ISSUE TITLE
[Solved]citations can not be rendered

### ISSUE THREAD

**Issue by nirvana6** [wzpan/hexo-renderer-pandoc#4]
I have installed hexo-renderer-pandoc, and followed the tutorial in Readme.md. 

---
## Problem

However, the citation can't show as excepted. ( Cf. §Conclusion on page http://bitwan.science/2015/10/21/ch2-1-9-Changing-the-case-geometry/ )

I read a lot of your Chinese Blog, and knew that hexo-renderer-pandoc may not work well with hexo 3.0. However, I am just using Hexo 3.1.1.
## My Configuration
- My working environment is as bellow: 

``` shell
hexo 3.1.1
pandoc 1.15.0.6
pandoc-citeproc 0.7.2
```
- The configuration involving hexo-renderer-pandoc is : 

``` shell
pandoc:
  filters:
    - pandoc-citeproc
  extra:
    - bibliography: "/path/to/bibfile.bib"
```
- Hexo theme is `Next` ( https://github.com/iissnan/hexo-theme-next )

**Comment by nirvana6** [comment]
General pandoc syntax can be rendered, but the citation using pandoc-citeproc still couldn't resolve.

I wonder if the "filters" entry within site's  _configure.yml  ever works on earth. But the log of `hexo server --debug` doesn't give any clue. 

Filter is very important to me because I rely on pandoc-crossref when writing. 

Thanks.

**Comment by nirvana6** [comment]
Problem solved. 

### Solution

I pull the lastest `hexo-renderer-pandoc` from github.

### Cause of Problem

The plugin installed by `npm install hexo-renderer-pandoc --save`  is too old.

**Comment by wzpan** [comment]
Hi @nirvana6 ,

Thanks for report that. I will update the npm package later.
