### ISSUE TITLE
The task list or todo list cannot be rendered correctly

### ISSUE THREAD

**Issue by zhaofei2048** [wzpan/hexo-renderer-pandoc#42]
This is displayed in Typora:
![image](https://user-images.githubusercontent.com/29796325/113692997-b35ddf80-9700-11eb-8855-f25e66aef668.png)
And below is what displayed on my website (rendered by hexo-renderer-pandoc):
![image](https://user-images.githubusercontent.com/29796325/113693498-3f700700-9701-11eb-83df-421ee2d0e25a.png)

It seems that task list (or called todo list) is not rendered correctly. However, pandoc group stated that it support the task list in their document:
![image](https://user-images.githubusercontent.com/29796325/113693879-aa214280-9701-11eb-82cc-a701d6560b74.png)
And when I run `pandoc --list-extensions`, I cannot find that extension (task_lists). My pandoc version is 2.2.3.2. Is my pandoc version too old?
Thanks a lot!

**Comment by Ritsuka314** [comment]
I think task_lists extention is introduced in 2.6: https://www.pandoc.org/releases.html#pandoc-2.6-2019-01-30

**Comment by zhaofei2048** [comment]
Ok, thank you very much!



---Original---
From: ***@***.***&gt;
Date: Tue, Apr 6, 2021 18:57 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wzpan/hexo-renderer-pandoc] The task list or todo list cannot be rendered correctly (#42)




 
I think task_lists extention is introduced in 2.6: https://www.pandoc.org/releases.html#pandoc-2.6-2019-01-30
