### ISSUE TITLE
about env of pandoc

### ISSUE THREAD

**Issue by wkmyws** [wzpan/hexo-renderer-pandoc#44]
I see :
 ```
var res = spawnSync("pandoc", args, {
    cwd: process.cwd(),
    env: process.env,
    encoding: "utf8",
    input: src
  });
```
could I use config like "env: /path/pandoc" and use the pandoc that is located in the certain path:
 ```
var res = spawnSync(config.env, args, {
    cwd: process.cwd(),
    env: process.env,
    encoding: "utf8",
    input: src
  });
```

**Comment by ChenglinYu** [comment]
收到

**Comment by Ritsuka314** [comment]
Hi @wkmyws 

Thanks for suggesting. I have updated the new 0.3.1 version. The following is also in `readme.md`.

By default, this plugin issues command `pandoc` to invoke pandoc. If your pandoc executable is not in your search path environment variable, you can override this command through `_config.yml`.

``` yml
pandoc:
  pandoc_path: C:/Program Files/Pandoc/pandoc.exe
```

Using absolute path is recommended.

The path depends on your operation system. So even if you are using the git-bash shell on Windows, you need the Windows path like the one in the example.

**Comment by wkmyws** [comment]
thank you for your job😊
