### ISSUE TITLE
📢 This repo has been transfered to hexojs organization

### ISSUE THREAD

**Issue by wzpan** [wzpan/hexo-renderer-pandoc#49]
Dear all,

It's obvious that I haven't maintained this repo for quite a long time, thanks to the help of @Ritsuka314 as a better contributor.

I think a better way to keep this plugin alive is to devote it to the [hexojs](https://github.com/hexojs) community. 

So I did it. 😄

**Comment by yoshinorin** [comment]
Honestly, we (the current active maintainers) are very busy and cannot maintain additional plugins. Actually, we archived some packages (not sure but maybe almost 10 packages) within the past year. Personally, I want to drop more plugins from the hexojs org.

Especially, this plugin doesn't have any test code. We can't understand correct behavior. Therefore, there is a high probability that it cannot be maintained.

**Comment by yoshinorin** [comment]
cc: @hexojs/core

**Comment by yoshinorin** [comment]
cc: @wzpan @Ritsuka314

**Comment by wzpan** [comment]
Well, I don't think the current active maintainers should watch all the plugins. That's why there is a sub team named ["Plugins"](https://github.com/orgs/hexojs/teams?query=%40wzpan) and why I was invited as one of the member of it. Isn't it? :) 
Currently no test inside the repo - for sure. It's a good idea to have some. Maybe we should add it later? @Ritsuka314

**Comment by yoshinorin** [comment]
@wzpan 

> Well, I don't think the current active maintainers should watch all the plugins. That's why there is a sub team named ["Plugins"](https://github.com/orgs/hexojs/teams?query=%40wzpan) and why I was invited as one of the member of it. Isn't it? :)

As far as I know all of the `Plugin team` members are inactive from at least end of 2018. I joined hexojs orgs in Oct 2018. I have not seen any activity from this team. Also `Theme team`.

So, actually the `Core team` maintaining most of the plugins and themes.

> It's a good idea to have some. Maybe we should add it later? @Ritsuka314

Anyway I will send invitation to @Ritsuka314 if needed.

**Comment by Ritsuka314** [comment]
I am still (very occationally) maintaining the plugin. It is mostly functional; most of the issues are related to pandoc itself rather than to the plugin. That is because all the plugin does is pass arguments and post contents to pandoc.

There is however an ongoing issue that we may need to re-develop the argument interface #54.

I don't think this plugin need any test, really.

**Comment by Ritsuka314** [comment]
Good news: I've put some tests for this plugin!

**Comment by wzpan** [comment]
> I don't think this plugin need any test, really.

I agree. Even my [hexo-generator-search](https://github.com/wzpan/hexo-generator-search) has no tests at all. 

But till now it still works well.
