### ISSUE TITLE
Hi, pandoc markdown renderer imcompletely in rendering markdown file.

### ISSUE THREAD

**Issue by Ytinifni-zc** [wzpan/hexo-renderer-pandoc#6]
Thank you for the plugin of hexo pandoc.

I found in my blog, renderer not works well in especially the list of md files. For example, when I write "1. ... 2. ... 3. ..." or "- ... - ..." in md files, renderer give me an ordinary result in html instead of element such as "\<li\>\</li\>".

Here is my blog : http://blog.ytinifni.net/

**Comment by Ytinifni-zc** [comment]
Oh, I wonder to show the code in html \<li\>\<\li\>.

**Comment by wzpan** [comment]
It shouldn't happen. Have you write such contents in multiple lines?

**Comment by Ytinifni-zc** [comment]
Yes, I write the list element in multiple lines. And I tried number list and dot list, but both of them were failed. Like the picture:
![](http://blog.ytinifni.net/image/failed_1.png)
and
![](http://blog.ytinifni.net/image/failed_2.png)

Sorry about the Chinese pictures.

**Comment by wzpan** [comment]
I see. You should leave an empty line before list. *e.g.*

```
数据仓库的几个挑战：

1. XXX
2. XXX
3. XXX
```

**Comment by Ytinifni-zc** [comment]
Seems there are a little differences of pandoc and markdown. 
Thank you very much!

**Comment by wzpan** [comment]
The original markdown requires that too.
It's a good practice to separate different *blocks* with empty line.

**Comment by jdhao** [comment]
Yes, indeed. Pandoc is strict about that. Before `list`, `table` and `quotation`, you must leave out a blank line. Or the generated html will not be what you want.
