### ISSUE TITLE
pandoc 渲染 GFM 格式，转换成 html 显示不太正确

### ISSUE THREAD

**Issue by longluo** [wzpan/hexo-renderer-pandoc#64]
### Check List

- [X] I have already read README.
- [X] I have already searched existing issues.
- [X] I have already searched existing pull requrests.

### Feature Request

I used this config to render the markdown:

I use this, but it doesn't woks.

```txt
pandoc:
  args:
    - "-f"
    - "gfm"
    - "-t"
    - "html"
    - "--mathjax"
```

but the rendered html is this：

![捕获1](https://github.com/hexojs/hexo-renderer-pandoc/assets/3395062/357098d8-9dd6-4430-987d-7a3b7805d3b4)

what we want to rendered out result is:

![捕获2](https://github.com/hexojs/hexo-renderer-pandoc/assets/3395062/d99d74d3-a3da-4249-9fb2-d5f7611b6ce9)

I have seen that hugo can render well, so I wonder why!

**Comment by Ritsuka314** [comment]
Please continue the discussion in the original issue report #63
