### ISSUE TITLE
请问，要如何配置可以让图片的alt展示在图片下面呢（即caption）

### ISSUE THREAD

**Issue by skyue** [wzpan/hexo-renderer-pandoc#8]
虽然常折腾博客，但并不是太懂编程，有两个问题咨询下：

1.  要如何配置可以让图片的alt属性展示在图片下面呢（即caption）
2. 安装pandoc再安装这个插件之后，不需要其它设置，执行`hexo -g`就会默认使用pandoc生成吗？

**Comment by wzpan** [comment]
1. 由主题决定，你可以通过定制主题实现这个效果。hexo-theme-freemind 即是将 alt 展示在图片下方的。
2. 最好将其他的markdown渲染器都删除。删除node_modules下其他的markdown渲染器，然后在根 _config.yml 里将 hexo-renderer-pandoc 添加进 plugin 列表。

**Comment by skyue** [comment]
搞定，多谢，
